USE [master]
GO

/****** Object:  Database [CNPV_2018]    Script Date: 29/08/2024 7:11:46 p. m. ******/
CREATE DATABASE [CNPV_2018]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CNPV_2018', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\CNPV_2018.mdf' , SIZE = 1581056KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CNPV_2018_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\CNPV_2018_log.ldf' , SIZE = 1122304KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CNPV_2018].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CNPV_2018] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CNPV_2018] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CNPV_2018] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CNPV_2018] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CNPV_2018] SET ARITHABORT OFF 
GO

ALTER DATABASE [CNPV_2018] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CNPV_2018] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CNPV_2018] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CNPV_2018] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CNPV_2018] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CNPV_2018] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CNPV_2018] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CNPV_2018] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CNPV_2018] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CNPV_2018] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CNPV_2018] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CNPV_2018] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CNPV_2018] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CNPV_2018] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CNPV_2018] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CNPV_2018] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CNPV_2018] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CNPV_2018] SET RECOVERY FULL 
GO

ALTER DATABASE [CNPV_2018] SET  MULTI_USER 
GO

ALTER DATABASE [CNPV_2018] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CNPV_2018] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CNPV_2018] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CNPV_2018] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CNPV_2018] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CNPV_2018] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CNPV_2018] SET QUERY_STORE = ON
GO

ALTER DATABASE [CNPV_2018] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [CNPV_2018] SET  READ_WRITE 
GO


